# Generated by Django 4.1 on 2022-08-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animal",
            old_name="trait",
            new_name="traits",
        ),
    ]
