# Generated by Django 4.0.6 on 2022-08-23 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('traits', '0001_initial'),
        ('animals', '0003_animal_created_at_animal_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals_group', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='traits',
            field=models.ManyToManyField(related_name='animals_traits', to='traits.trait'),
        ),
    ]
